select CUSTOMER.C_NAME, O.O_ORDERKEY, SUM(L.L_QUANTITY*(L.L_EXTENDEDPRICE - L.L_DISCOUNT)) as s
from (LINEITEM L join ORDERS O on L.L_ORDERKEY = O.O_ORDERKEY ) join CUSTOMER on CUSTOMER.C_CUSTKEY == O.O_CUSTKEY
group by O.O_ORDERKEY order by s DESC limit 20;


-- select l.L_ORDERKEY as key, l.L_QUANTITY*(l.L_EXTENDEDPRICE - l.L_DISCOUNT) as size from LINEITEM l
-- where (select count(*) from LINEITEM r
--         where (r.L_QUANTITY*(r.L_EXTENDEDPRICE - r.L_DISCOUNT) > l.L_QUANTITY*(l.L_EXTENDEDPRICE - l.L_DISCOUNT))<=20
--     and l.L_ORDERKEY != r.L_ORDERKEY
--     ) order by size DESC ;

--order by ranks as r
--Part 2-1
select N.N_NAME, SUM(L.L_QUANTITY*(L.L_EXTENDEDPRICE - L.L_DISCOUNT))
from NATION N, LINEITEM L, SUPPLIER S
where N.N_NATIONKEY == S.S_NATIONKEY and S.S_SUPPKEY == L.L_SUPPKEY and
      L.L_ORDERKEY in (select O.O_ORDERKEY
                       from CUSTOMER C, ORDERS O, LINEITEM L1
                       where C.C_CUSTKEY == O.O_CUSTKEY and C.C_NATIONKEY == N.N_NATIONKEY
                         and O.O_ORDERKEY == L1.L_ORDERKEY and L1.L_ORDERKEY == L.L_ORDERKEY)
group by N_NATIONKEY order by N.N_NAME COLLATE NOCASE;

--part 2.2
SELECT N.N_NAME, SUM(L.L_QUANTITY*(L.L_EXTENDEDPRICE - L.L_DISCOUNT)) as s
from NATION N, LINEITEM L, SUPPLIER S, CUSTOMER C, ORDERS O
where (S.S_NATIONKEY == C.C_NATIONKEY and S.S_SUPPKEY == L.L_SUPPKEY
           and C.C_CUSTKEY == O.O_CUSTKEY and O.O_ORDERKEY == L.L_ORDERKEY
            and S.S_NATIONKEY == N.N_NATIONKEY and N.N_NATIONKEY == C.C_NATIONKEY)
group by N.N_NATIONKEY ORDER BY N.N_NAME COLLATE NOCASE;


--Part 3 TODO:
with inside (name, Nkey, Rkey, value) as (SELECT N.N_NAME, N.N_NATIONKEY, N.N_REGIONKEY, SUM(L.L_QUANTITY*(L.L_EXTENDEDPRICE - L.L_DISCOUNT)) as s
from NATION N, LINEITEM L, SUPPLIER S, CUSTOMER C, ORDERS O, NATION N1
where (S.S_NATIONKEY == N.N_NATIONKEY and S.S_SUPPKEY == L.L_SUPPKEY
           and C.C_CUSTKEY == O.O_CUSTKEY and O.O_ORDERKEY == L.L_ORDERKEY
            and N1.N_NATIONKEY == C.C_NATIONKEY and N.N_REGIONKEY == N1.N_REGIONKEY)
group by N.N_NATIONKEY)
--main clause
SELECT I.name, I.value, SUM(L1.L_QUANTITY*(L1.L_EXTENDEDPRICE - L1.L_DISCOUNT)) as s1
from NATION N1, LINEITEM L1, SUPPLIER S1, CUSTOMER C1, ORDERS O1, NATION N2, inside as I
where (N2.N_NATIONKEY == C1.C_NATIONKEY and C1.C_CUSTKEY == O1.O_CUSTKEY and O1.O_ORDERKEY == L1.L_ORDERKEY
            and N1.N_NATIONKEY == S1.S_NATIONKEY and S1.S_SUPPKEY == L1.L_SUPPKEY and N1.N_REGIONKEY != N2.N_REGIONKEY
            and N1.N_NATIONKEY == I.Nkey)
group by N1.N_NATIONKEY ORDER BY I.value DESC limit 2;

--test
select N.N_NAME,N.N_NATIONKEY, N.N_REGIONKEY, SUM(L1.L_QUANTITY*(L1.L_EXTENDEDPRICE - L1.L_DISCOUNT)) as s1
from NATION N, LINEITEM L1, SUPPLIER S
where N.N_NATIONKEY == S.S_NATIONKEY and S.S_SUPPKEY == L1.L_SUPPKEY and
      L1.L_ORDERKEY in (select O.O_ORDERKEY
                        from CUSTOMER C, ORDERS O,  NATION N1
                        where C.C_CUSTKEY == O.O_CUSTKEY and C.C_NATIONKEY == N1.N_NATIONKEY
                          and O.O_ORDERKEY == L1.L_ORDERKEY
                          and N.N_REGIONKEY != N1.N_REGIONKEY)
group by N_NATIONKEY order by s1 DESC limit 2;

--test
SELECT N.N_NAME, N.N_NATIONKEY, N.N_REGIONKEY, SUM(L.L_QUANTITY*(L.L_EXTENDEDPRICE - L.L_DISCOUNT)) as s
from NATION N, LINEITEM L, SUPPLIER S, CUSTOMER C, ORDERS O, NATION N1
where (S.S_NATIONKEY == N.N_NATIONKEY and S.S_SUPPKEY == L.L_SUPPKEY
           and C.C_CUSTKEY == O.O_CUSTKEY and O.O_ORDERKEY == L.L_ORDERKEY
            and N1.N_NATIONKEY == C.C_NATIONKEY and N.N_REGIONKEY == N1.N_REGIONKEY) group by N.N_NATIONKEY
order by s DESC limit 2;

--test
SELECT N.N_NAME, SUM(L.L_QUANTITY*(L.L_EXTENDEDPRICE - L.L_DISCOUNT)) as s1
from NATION N, LINEITEM L, SUPPLIER S, CUSTOMER C, ORDERS O, NATION N1
where (N1.N_NATIONKEY == C.C_NATIONKEY and C.C_CUSTKEY == O.O_CUSTKEY and O.O_ORDERKEY == L.L_ORDERKEY
            and N.N_NATIONKEY == S.S_NATIONKEY and S.S_SUPPKEY == L.L_SUPPKEY and N1.N_REGIONKEY != N.N_REGIONKEY )
group by N.N_NATIONKEY ORDER BY s1 DESC limit 2;

--test all
with inside (name, Nkey, Rkey, value) as (SELECT N.N_NAME, N.N_NATIONKEY, N.N_REGIONKEY, SUM(L.L_QUANTITY*(L.L_EXTENDEDPRICE - L.L_DISCOUNT)) as s
from NATION N, LINEITEM L, SUPPLIER S, CUSTOMER C, ORDERS O, NATION N1
where (S.S_NATIONKEY == N.N_NATIONKEY and S.S_SUPPKEY == L.L_SUPPKEY
           and C.C_CUSTKEY == O.O_CUSTKEY and O.O_ORDERKEY == L.L_ORDERKEY
            and N1.N_NATIONKEY == C.C_NATIONKEY and N.N_REGIONKEY == N1.N_REGIONKEY)
group by N.N_NATIONKEY)
--main clause
SELECT I.name, I.value, SUM(L1.L_QUANTITY*(L1.L_EXTENDEDPRICE - L1.L_DISCOUNT)) as s1
from NATION N1, LINEITEM L1, SUPPLIER S1, CUSTOMER C1, ORDERS O1, inside as I
where (N1.N_NATIONKEY == C1.C_NATIONKEY and C1.C_CUSTKEY == O1.O_CUSTKEY and O1.O_ORDERKEY == L1.L_ORDERKEY
            and I.Nkey == S1.S_NATIONKEY and S1.S_SUPPKEY == L1.L_SUPPKEY and I.Rkey != N1.N_REGIONKEY)
group by I.Nkey ORDER BY I.value DESC limit 2;

--Part 4
select S.S_NAME as name, count(DISTINCT O.O_CUSTKEY) as s
from SUPPLIER S  join LINEITEM L join ORDERS O
    on S.S_SUPPKEY = L.L_SUPPKEY and O.O_ORDERKEY == L.L_ORDERKEY
group by S.S_SUPPKEY having s > 615
ORDER BY s DESC

